// Parser for vHost tab - host information
import type { VHostInfo } from '@/types';
import type { WorkSheet } from 'xlsx';
import { parseSheet, getStringValue, getNumberValue, getBooleanValue } from './utils';

const COLUMN_MAP: Record<string, keyof VHostInfo | null> = {
  'Name': 'name',
  'Host': 'name',
  'Host Name': 'name',
  'Config Status': 'configStatus',
  'Config status': 'configStatus',
  'Overall Status': 'overallStatus',
  'Overall status': 'overallStatus',
  'Power State': 'powerState',
  'Powerstate': 'powerState',
  'Connection State': 'connectionState',
  'Connection state': 'connectionState',
  'CPU Model': 'cpuModel',
  'Processor Type': 'cpuModel',
  'Speed': 'cpuMHz',
  'CPU MHz': 'cpuMHz',
  '# CPU': 'cpuSockets',
  'CPU Sockets': 'cpuSockets',
  'Sockets': 'cpuSockets',
  'Cores per Socket': 'coresPerSocket',
  'Cores per CPU': 'coresPerSocket',
  '# Cores': 'totalCpuCores',
  'Total Cores': 'totalCpuCores',
  'Hyperthreading': 'hyperthreading',
  'HT': 'hyperthreading',
  'CPU usage': 'cpuUsageMHz',
  'CPU Usage MHz': 'cpuUsageMHz',
  'Memory': 'memoryMiB',
  'Memory MiB': 'memoryMiB',
  'Memory MB': 'memoryMiB',
  'Memory usage': 'memoryUsageMiB',
  'Memory Usage MiB': 'memoryUsageMiB',
  'Memory Usage MB': 'memoryUsageMiB',
  '# VMs': 'vmCount',
  'VMs': 'vmCount',
  'VM Count': 'vmCount',
  '# vCPUs': 'vmCpuCount',
  'VM CPU Count': 'vmCpuCount',
  'VM Memory': 'vmMemoryMiB',
  'VM Memory MiB': 'vmMemoryMiB',
  'Vendor': 'vendor',
  'Model': 'model',
  'ESXi Version': 'esxiVersion',
  'ESX Version': 'esxiVersion',
  'Version': 'esxiVersion',
  'Build': 'esxiBuild',
  'ESXi Build': 'esxiBuild',
  'Datacenter': 'datacenter',
  'Cluster': 'cluster',
  'Uptime': 'uptimeSeconds',
  'Uptime (s)': 'uptimeSeconds',
};

export function parseVHost(sheet: WorkSheet): VHostInfo[] {
  const rows = parseSheet(sheet, COLUMN_MAP);

  return rows.map((row): VHostInfo => ({
    name: getStringValue(row, 'name'),
    configStatus: getStringValue(row, 'configStatus'),
    overallStatus: getStringValue(row, 'overallStatus'),
    powerState: getStringValue(row, 'powerState'),
    connectionState: getStringValue(row, 'connectionState'),
    cpuModel: getStringValue(row, 'cpuModel'),
    cpuMHz: getNumberValue(row, 'cpuMHz'),
    cpuSockets: getNumberValue(row, 'cpuSockets'),
    coresPerSocket: getNumberValue(row, 'coresPerSocket'),
    totalCpuCores: getNumberValue(row, 'totalCpuCores'),
    hyperthreading: getBooleanValue(row, 'hyperthreading'),
    cpuUsageMHz: getNumberValue(row, 'cpuUsageMHz'),
    memoryMiB: getNumberValue(row, 'memoryMiB'),
    memoryUsageMiB: getNumberValue(row, 'memoryUsageMiB'),
    vmCount: getNumberValue(row, 'vmCount'),
    vmCpuCount: getNumberValue(row, 'vmCpuCount'),
    vmMemoryMiB: getNumberValue(row, 'vmMemoryMiB'),
    vendor: getStringValue(row, 'vendor'),
    model: getStringValue(row, 'model'),
    esxiVersion: getStringValue(row, 'esxiVersion'),
    esxiBuild: getStringValue(row, 'esxiBuild'),
    datacenter: getStringValue(row, 'datacenter'),
    cluster: getStringValue(row, 'cluster'),
    uptimeSeconds: getNumberValue(row, 'uptimeSeconds'),
  })).filter(host => host.name);
}
